version: '3'
services:
  os-node:
    image: opensearchproject/opensearch:2.1.0
    container_name: os-node
    environment:
      - cluster.name=os-cluster
      - node.name=os-node 
      - "DISABLE_INSTALL_DEMO_CONFIG=true"      
      - "DISABLE_SECURITY_PLUGIN=true"
      - "discovery.type=single-node"
      - "JAVA_HOME: /usr/share/opensearch/jdk"          
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - os-data:/usr/share/opensearch/data
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - os-net 
  os-dashboards:
    image: opensearchproject/opensearch-dashboards:2.1.0
    container_name: os-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://os-node:9200"]' # must be a string with no spaces when specified as an environment variable
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: true
    networks:
      - os-net

volumes:
  os-data:  

networks:
  os-net:
